version: '3.9'

#__author__ = "Nghia Doan"
#__company__ = "Agiga Quanta Inc."
#__copyright__ = "Copyright 2021"
#__version__ = "0.1.0"
#__maintainer__ = "Nghia Doan"
#__email__ = "nghia71@gmail.com"
#__status__ = "Development"

##############################################################################
#
# services
#
##############################################################################
services:

##############################
# common services
#

  ####################
  # tika:
  #
  tika:
    image: apache/tika:2.1.0
    hostname: tika
    container_name: tika
    ports:
      - 9998:9998

  ####################
  # stanford_nlp:
  #
  stanford_nlp:
    build:
      context: ./stanford_nlp
      dockerfile: Dockerfile
    image: agigaquanta/stanford_nlp:1.0.0
    hostname: stanford_nlp
    container_name: stanford_nlp
    ports:
      - 9000:9000


##############################
# data processing services
#

  ####################
  # pdf_extractor:
  #
  pdf_extractor:
    build:
      context: ./pdf_extractor
      dockerfile: Dockerfile
    image: agigaquanta/pdf_extractor:1.0.0
    hostname: pdf_extractor
    container_name: pdf_extractor
    volumes:
      - ./data/pdf:/pdf
      - ./data/xhtml:/xhtml

  ####################
  # doc_processor:
  #
  doc_processor:
    build:
      context: ./doc_processor
      dockerfile: Dockerfile
    image: agigaquanta/doc_processor:1.0.0
    hostname: doc_processor
    container_name: doc_processor
    volumes:
      - ./conf:/conf
      - ./data/xhtml:/xhtml
      - ./data/json:/json
      - ./data/nlp:/nlp
      - ./data/txt:/txt
      - ./data/images:/images
