version: '3.9'

#__author__ = "Nghia Doan"
#__company__ = "Agiga Quanta Inc."
#__copyright__ = "Copyright 2021"
#__version__ = "0.1.0"
#__maintainer__ = "Nghia Doan"
#__email__ = "nghia71@gmail.com"
#__status__ = "Development"

##############################################################################
#
# services
#
##############################################################################
services:

##############################
# common services
#

  ####################
  # tika:
  #
  tika:
    image: apache/tika:2.1.0
    hostname: tika
    container_name: tika
    networks:
      - backend
    ports:
      - 9998:9998

  ####################
  # nltk_nlp:
  #
  nltk_nlp:
    build:
      context: ./nltk_nlp
      dockerfile: Dockerfile
    image: agigaquanta/nltk_nlp:1.0.0
    hostname: nltk_nlp
    container_name: nltk_nlp
    networks:
      - backend
    ports: 
      - 7000:6543

  ####################
  # stanford_nlp:
  #
  stanford_nlp:
    build:
      context: ./stanford_nlp
      dockerfile: Dockerfile
    image: agigaquanta/stanford_nlp:1.0.0
    hostname: stanford_nlp
    container_name: stanford_nlp
    networks:
      - backend
    ports:
      - 9000:9000

  ####################
  # neo4j:
  # - Neo4j + APOC + GDS
  #
  neo4j:
    image: neo4j:4.4.3
    hostname: neo4j
    container_name: neo4j
    networks:
      - backend
    ports:
      - 7474:7474
      - 7473:7473
      - 7687:7687
    volumes:
      - ./neo4j/data:/data
      - ./data/json:/import
      - ./neo4j/logs:/logs
      - ./neo4j/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/path_poc
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_memory_heap_initial__size=2G
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*
      - NEO4J_dbms_security_allow__csv__import__from__file__urls=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_jobs_pool_num__threads=4
      - NEO4J_apoc_jobs_scheduled_num__threads=4
      # - NEO4J_apoc_spatial_geocode_provider=osm
      # - NEO4J_apoc_spatial_geocode_osm_throttle=5000

##############################
# data processing services
#

  ####################
  # pdf_extractor:
  #
  pdf_extractor:
    build:
      context: ./pdf_extractor
      dockerfile: Dockerfile
    image: agigaquanta/pdf_extractor:1.0.0
    hostname: pdf_extractor
    container_name: pdf_extractor
    networks:
      - backend
    volumes:
      - ./data/pdf:/pdf
      - ./data/xhtml:/xhtml

  ####################
  # doc_processor:
  #
  doc_processor:
    build:
      context: ./doc_processor
      dockerfile: Dockerfile
    image: agigaquanta/doc_processor:1.0.0
    hostname: doc_processor
    container_name: doc_processor
    networks:
      - backend
    volumes:
      - ./src:/src
      - ./conf:/conf
      - ./data/xhtml:/xhtml
      - ./data/json:/json

##############################
# data visualization services
#

  ####################
  # neodash:
  #
  neodash:
    image: nielsdejong/neodash:latest
    hostname: neodash
    container_name: neodash
    networks:
      - backend
    ports:
      - 8000:80

################################################################################
#
# networks
#
################################################################################
networks:
  backend:
    name: backend
